### ISSUE TITLE
Error when decrypting messages

### ISSUE THREAD

**Issue by ehsanecc** [bitonic/wadump#5]
Hi, the process of fetching seems works fine but when it tries to decrypt this error occurs:
```
could not decode message false_989192994024@c.us_11649B46092CD16ADC662B6805DF2580 unimplemented wire type 1
decryptMessage @ Script snippet #1:301
```
Probably because of WhatsApp's new encryption method?

**Comment by bitonic** [comment]
https://github.com/bitonic/wadump/commit/0121931ca082bced1aedfe671b49f377380893f6 should fix it, can you test?
